POST http://localhost:3000/api/auth/register
Content-Type: application/json


{
    "username": "hoangle",
    "password": "hoangleee"
}

################################ login

POST http://localhost:3000/api/auth/login
Content-Type: application/json


{
    "username": "admin",
    "password": "123"
}

########### Post Login
POST http://localhost:3000/api/post 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjljYmZjNmQ5ZGRhMDhhZmI1ODk1M2MiLCJpYXQiOjE2NTQ0Mzk4Nzh9.b16VsyTLbTG0SdU8YR4OhwW2SoOjkmNh5p-o2wnqC5U


{
    "title": "ssasa",
    "description": "Welcome",
    "url": "google.com",
    "status": ""
}

##############3

GET http://localhost:3000/api/post 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjljYmZjNmQ5ZGRhMDhhZmI1ODk1M2MiLCJpYXQiOjE2NTQ0Mzk4Nzh9.b16VsyTLbTG0SdU8YR4OhwW2SoOjkmNh5p-o2wnqC5U
