POST http://localhost:5000/api/auth/register
Content-Type: application/json


{
    "username": "admin",
    "password": "123"
}

################################ login

POST http://localhost:5000/api/auth/login
Content-Type: application/json


{
    "username": "hoanglew2q",
    "password": "hoangleeew"
}

########### Post Login
POST http://localhost:5000/api/post 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjljZGViZGJiZjhlYTI5YWMyNTg0MWUiLCJpYXQiOjE2NTQ0NDc4Nzd9.FAUDkMKHK8nAET7b4Th2cx_Drx7v0pDYWSlQXX4v0nk


{
    "title": "ssasa",
    "description": "Welcome",
    "url": "google.com",
    "status": ""
}

##############3

GET http://localhost:5000/api/post 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjljZGViZGJiZjhlYTI5YWMyNTg0MWUiLCJpYXQiOjE2NTQ0NDc4Nzd9.FAUDkMKHK8nAET7b4Th2cx_Drx7v0pDYWSlQXX4v0nk


#########
PUT http://localhost:5000/api/post/629cdf10bbf8ea29ac258427
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjljZGViZGJiZjhlYTI5YWMyNTg0MWUiLCJpYXQiOjE2NTQ0NDc4Nzd9.FAUDkMKHK8nAET7b4Th2cx_Drx7v0pDYWSlQXX4v0nk

{
  "title": "Vue",
  "description": "VUEEEEE",
  "url": "https://vuejs.org",
  "status": "LEARNING"
}

#####
DELETE http://localhost:5000/api/post/629cdf10bbf8ea29ac258427
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjljZGViZGJiZjhlYTI5YWMyNTg0MWUiLCJpYXQiOjE2NTQ0NDc4Nzd9.FAUDkMKHK8nAET7b4Th2cx_Drx7v0pDYWSlQXX4v0nk

